version: 2

jobs:
  build:
    docker:
      - image: node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  deploy:
    docker:
      - image: node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run start

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
